name: Linux Build Test
on:
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - uses: cachix/cachix-action@v6
      with:
        name: digitallyinduced
        skipPush: true

    - run: |
          nix-env -iA nixpkgs.direnv
          nix-env -f https://ihp.digitallyinduced.com/ihp-new.tar.gz -i ihp-new
          ihp-new blog
