name: Binary Build
on:
  push:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/c7f75838c360473805afcf5fb2fa65e678efd94b.tar.gz
    - uses: cachix/cachix-action@v8
      with:
        name: digitallyinduced
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: |
          git clone https://github.com/digitallyinduced/ihp-boilerplate.git
          cd ihp-boilerplate
          git checkout nixpkgs-update
          echo "<?php" >> replace.php
          echo "\$file_contents = file_get_contents('./default.nix');" >> replace.php
          echo '$new_content = preg_replace("/\".{40}\"/", "\"$argv[1]\"", $file_contents);' >> replace.php
          echo '$new_content_with_ref = preg_replace("/ihp = builtins.fetchGit {/", "ihp = builtins.fetchGit {        ref = \"*\";", $new_content);' >> replace.php
          echo '$new_content_with_ref = str_replace("p.ihp", "p.ihp wreq mmark mmark-ext strip-ansi-escape stripe-signature stripe-concepts http-conduit units units-defs haskell-to-elm aeson-casing", $new_content_with_ref);' >> replace.php
          echo "file_put_contents('./default.nix', \$new_content_with_ref);" >> replace.php
          echo "?>" >> replace.php
          php replace.php $GITHUB_SHA
          cat default.nix
          nix-shell --run "echo 'It worked'"
