name: Check PR compiles without errors
on:
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/c7f75838c360473805afcf5fb2fa65e678efd94b.tar.gz
    - uses: cachix/cachix-action@v8
      with:
        name: digitallyinduced
        skipPush: true

    - run: |
          cd $GITHUB_WORKSPACE
          mkdir -p ~/.config/nixpkgs
          echo "{ allowBroken = true; }" >> ~/.config/nixpkgs/config.nix
          nix-shell --run "cabal build"
