name: Check PR compiles without errors
on:
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/38da06c69f821af50323d54b28d342cc3eb42891.tar.gz
    - uses: cachix/cachix-action@v10
      with:
        name: digitallyinduced
        skipPush: true

    - run: |
          cd $GITHUB_WORKSPACE
          mkdir -p ~/.config/nixpkgs
          echo "{ allowBroken = true; }" >> ~/.config/nixpkgs/config.nix
          nix-shell --run "cabal build --flag FastBuild"
