name: "Tests"
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/a95ed9fe764c3ba2bf2d2fa223012c379cd6b32e.tar.gz
    - uses: cachix/cachix-action@v12
      with:
        name: digitallyinduced
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Install devenv.sh
      run: nix profile install --accept-flake-config github:cachix/devenv/latest
    - run: devenv shell tests
