name: "Tests"
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/d50679e56e4a3311155eb97dcaa55db52b2c2d5a.tar.gz
    - uses: cachix/cachix-action@v8
      with:
        name: digitallyinduced
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --run "runghc $(make -f lib/IHP/Makefile.dist print-ghc-extensions) -iIDE Test/Main.hs"
